# Proximal Policy Optimization

### Import the libraries

In [2]:
# Calculations
import numpy as np
from numpy import random, sqrt

# Network libraries
import torch
import torch.nn.functional as F, torch.nn as nn, torch.optim as optim
from torch.distributions import Normal as Normal

# Game library
from TicTacToe import initialState, randomState, printState, drawState, move, possibleMoves, isOver, gameScore

In [15]:
printState(randomState())

[[ 0  0 -1]
 [ 0  1  0]
 [ 1  0  0]]
